// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type UserSummary struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	PostCount int32  `json:"postCount"`
}
